---
title: "Instacart"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill

---

```{r,include=FALSE, message=FALSE}
library(flexdashboard)
library(plotly)
library(tidyverse)
library(plotly)
library(p8105.datasets)
data("instacart")
dow_labels <- c("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat")
```
Column {data-width=650}
-----------------------------------------------------------------------

### 1. Barchart : the number of items ordered in each aisle (more than 10000 items ordered)
```{r, warning=FALSE}
# make a plot that show number of items
instacart_plot =
  instacart |>
  group_by(aisle) |>
  summarize(count = n()) |>
  filter(count> 10000) |>
   mutate(
    aisle = factor(aisle),
    aisle = fct_reorder(aisle, count)
  ) |>
  	plot_ly(x = ~aisle,
					y = ~count,
					color = ~aisle,
					type = "bar") 
  
instacart_plot
```

Column {data-width=350}
-----------------------------------------------------------------------

### 2. Box plot :Frequency and number of items in an order

```{r}
# plotly, order frequency and number of items in an order
instacart |>
	group_by(order_id)|>
	mutate(items_ordered = n()) |>
	distinct(items_ordered, days_since_prior_order) |>
	plot_ly(x = ~as.factor(days_since_prior_order),
					y = ~log(items_ordered),
					type = "box") |>
	layout(
				 xaxis = list(title = "Days since prior order (Day)"),
				 yaxis = list(title = "Log (order size)")
				 )

```

-----------------------------------------------------------------------
### 3.  scatterplot shows the typical time and day of the week that items get ordered more than 5000.

```{r, warning=FALSE}
instacart |>
   group_by(aisle, order_dow) |>
  summarize(count = n(),
            mean_hour = mean(order_hour_of_day, na.rm = TRUE), .groups = "drop")  |>
  filter(count> 5000) |>
    plot_ly(
    x = ~order_dow,
    y = ~mean_hour,
    color = ~ aisle,
    type = "scatter",
    mode = "lines+markers+text"
      )
```

Go back to the [homepage](index.html).
