---
title: "Highlight Publications"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

Jenni A. Shearston; Milo Gordon; Vivian Do; Kristen Upson; Olgica Balac;**Khue Nguyen**; Beizhan Yan; Marianthi-Anna Kioumourtzoglou; Kathrin Schilling, “Tampons as a Source of Exposure to Metal(loid)”, Environmental Health Perspective. 

**Nguyen, K.**, Saxena, R., Re D.B., Yan, B., “Rapid LC-MS/MS quantification of Organophosphate non-specific metabolites in hair using alkaline extraction approach”, Journal of Chromatography B.

John, E.M., Keegan, T.H., Terry, M.B., Koo, J., Ingles, S.A., Nguyen, J.T, Thomsen, C., Santella, R.M., **Nguyen, K.**, Yan, B., “Urinary Biomarkers of Polycyclic Aromatic Hydrocarbons and timing of pubertal development: The California PAH study”, Epidemiology. 



**Nguyen, K.**, Pitirangon, M., Wu, H., John, E., Santella, R.M., Terry, M.B., Yan, B., Improvement on recovery and reproducibility for quantifying urinary mono-hydroxylated polycyclic aromatic hydrocarbons (OH-PAHs), Journal of Chromatography B.

John, E., Koo, J., Ingles, S.A, Keegan, T.H., Nguyen, J.T., Thomsen, C., Terry, M.B., Santella, R.M., **Nguyen, K.**, Yan, B., Predictors of urinary polycyclic aromatic hydrocarbon metabolites in girls from the San Francisco Bay Area, Environmental Research. 


Nghiem A., Shen, Y., Stahl M.,Sun J., Haque E.,, DeYoung B.,**Nguyen K.**,, Tran M., Pham T., Pham V., Mailloux, M., Harvey C.,van Geen L.,, Bostick B., “Upscaling in-situ sediment iron reduction observations to classify arsenic-susceptible aquifers”, Proceedings of the National Academy of Sciences.

Mailloux, M., Kim, C., Kichuk, T., **Nguyen, K.**, Precht, C.,Wang, S. , Jewell, T. ,Karaoz, U., Brodie, E., Williams, K. , Beller, H. , Buchholz, B.,“Paired RNA Radiocarbon and Sequencing Analyses Indicate the Importance of Autotrophy in a Shallow Alluvial Aquifer”, Scientific Report.

**Nguyen, K.**, Bostick, B., Pavilonis, B.,“Lead in New York City residential soils and its links with the rate of childhood elevated Blood lead level”, Poster at NY/NJ ERC 38th annual conference, 2017 and AIHce 2017 Seattle , Washington

Go back to the [homepage](index.html).
